layout: post
title: "US-RSE June 2026 Newsletter"
subtitle: "🤔 Arrestive Curiosity & RSEs: How to Turn the Shiny Toy Syndrome Bug into a Feature 🤔"
category: newsletter
tags: [newsletter, June]
date: 2026-06-15 00:00:00 -0400
author: "Tinashe M. Tapera (Author & Editor), Sandra Gesing (Editor), Ian Cosden (Editor)"
image: "/assets/img/newsletter-202606/us-rse_4k_members.png" #TODO
img_alttext: "Colourful poster with the words \"Celebrating 4,000+ Member Milestone\" and a progression of trees growing from a seedling to a full tree, with the number 4011 prominently displayed." #TODO
next_meeting_date: Thursday, July 9, 2026, 12:00PM EST #Done
sections:
  preamble: true #Done
  headline: true #Done
  conference: true #Done
  execupdate: false #TODO
  scupdate: false #TODO
  orgmember: true #TODO
  communityfunds: false #TODO
  news: true #TODO
  events: true #TODO
  reads: true #TODO
  involved: true
  jobs: true

